DROP TABLE IF EXISTS bronze.videos;
DROP TABLE IF EXISTS bronze.comments;

CREATE TABLE bronze.videos(
    video_id CHARACTER VARYING(11) PRIMARY KEY,
    channel_name TEXT,
    video_title TEXT,
    published_at TIMESTAMP,
    view_count BIGINT,
    like_count BIGINT,
    comment_count BIGINT
);

CREATE TABLE bronze.comments(
    comment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_id CHARACTER VARYING(11),
    comment_author TEXT,
    comment_text TEXT,
    like_count BIGINT,
    published_at TIMESTAMP,
    total_replies INTEGER,
    is_public BOOLEAN,
    CONSTRAINT fk_comments_videos
        FOREIGN KEY (video_id)
        REFERENCES bronze.videos(video_id)
);
